name: Deploy to EC2 Apache Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo yum update -y
            sudo yum install -y httpd
            sudo systemctl enable httpd
            sudo systemctl restart httpd
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ec2-user/site/* /var/www/html/
            echo "✅ Deployment Done"

